# Setup
url: http://www.redkingdreaming.com # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
title: redkingdreaming
tagline: the online portfolio of playwright steve yockey


collections:
  short:
    output: false
  full:
    output: false


exclude: ["_assets", "gulp", "node_modules", ".gulpfile", "package.json", "README.md"]
