backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Media files will be stored in the repo under this folder structure
media_folder: '_assets/images'
public_folder: 'assets/images'

collections:
  - label: 'Website Settings'
    name: 'website-settings'
    files:
      - label: 'SEO Settings'
        name: 'seo-settings'
        file: '_data/seo.json'
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: Description
            name: description
            widget: 'string'
            pattern: ['^.{120,158}$', 'Must be between 120 and 158 characters.']
      - label: 'Contact Info'
        name: 'contact-settings'
        file: '_data/contact.json'
        fields:
          - label: Email
            name: email
            widget: string
          - label: Twitter
            name: twitter
            widget: string

  - label: Content
    name: content
    files:
      - label: Bio
        name: bio
        file: '_data/bio.json'
        fields:
          - label: Bio
            name: bio
            widget: markdown
      - label: Slides
        name: slides
        file: '_data/slides.json'
        fields:
          - label: Photos
            name: photos
            widget: list
            fields:
              - label: Photo
                name: image
                widget: image
              - label: Title
                name: title
                widget: string
              - label: Tagline
                name: tagline
                widget: string
