backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Media files will be stored in the repo under this folder structure
media_folder: '_assets/images'
public_folder: 'assets/images'

collections:
  - label: 'Website Settings'
    name: 'website-settings'
    files:
      - label: 'SEO Settings'
        name: 'seo-settings'
        file: '_data/seo.json'
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: Description
            name: description
            widget: 'string'
            pattern: ['^.{120,158}$', 'Must be between 120 and 158 characters.']

      - label: 'Social Network Settings'
        name: 'social-settings'
        file: '_data/social.json'
        fields:
          - label: 'Twitter'
            name: 'twitter'
            widget: 'object'
            fields:
              - label: 'Name'
                name: 'name'
                widget: 'string'
              - label: 'Twitter Handle'
                name: 'url'
                widget: 'string'
      - label: 'Contact Info'
        name: 'contact-settings'
        file: '_data/contact.json'
        fields:
          - label: Email
            name: email
            widget: string

  - label: Content
    name: content
    files:
      - label: Profile
        name: profile
        file: '_data/profile.json'
        fields:
          - label: Bio
            name: bio
            widget: markdown
          - label: Profile Photo
            name: photo
            widget: image
      - label: Slides
        name: slides
        file: '_data/slides.json'
        fields:
          - label: Photos
            name: photos
            widget: list
            fields:
              - label: Photo
                name: image
                widget: image
              - label: Title
                name: title
                widget: string
              - label: Tagline
                name: tagline
                widget: string
      - label: Representation
        name: representation
        file: '_data/representation.json'
        fields:
          - label: Theater Rep
            name: theater
            widget: list
            fields:
              - label: Agent
                name: agent
                widget: string
              - label: Agency
                name: agency
                widget: string
              - label: Address
                name: address
                widget: object
                fields:
                  - label: Street
                    name: street
                    widget: string
                  - label: City
                    name: city
                    widget: string
                  - label: State
                    name: state
                    widget: string
                  - label: Zip
                    name: zip
                    widget: string
              - label: Phone
                name: phone
                widget: string
          - label: TV Rep
            name: television
            widget: list
            fields:
              - label: Agent
                name: agent
                widget: string
              - label: Agency
                name: agency
                widget: string
              - label: Address
                name: address
                widget: object
                fields:
                  - label: Street
                    name: street
                    widget: string
                  - label: City
                    name: city
                    widget: string
                  - label: State
                    name: state
                    widget: string
                  - label: Zip
                    name: zip
                    widget: string
              - label: Phone
                name: phone
                widget: string
